#!/home/mark/.nvm/versions/node/v15.5.0/bin/node

let Phrase = require("mrichardsjboit-palindrome");
let urllib = require('urllib');
let url = 'https://cdn.learnenough.com/phrases.txt';

urllib.request(url, { followRedirect: true },function (err, data, res) {
 if(err) {
   throw err;
 }

 let body = data.toString();
 let lines = body.split("\n")
 let palindromes = lines.filter(line => new Phrase(line).palindrome() );

 palindromes.forEach(function(palindrome)  {
  console.log("palindrome detected:", palindrome);
 });
});
